// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract CrowdTicket {
    struct Ticket {
        address owner;
        string eventId;
        bool isUsed;
        bool exists;
    }

    // Mapping from ticketId to Ticket struct
    mapping(string => Ticket) public tickets;

    // Events
    event TicketCreated(string ticketId, string eventId, address owner);
    event TicketUsed(string ticketId, string eventId);

    /**
     * @dev Create a new ticket
     * @param _ticketId unique identifier generated by backend
     * @param _eventId ID of the event
     */
    function createTicket(string memory _ticketId, string memory _eventId) public {
        require(!tickets[_ticketId].exists, "Ticket already exists");

        tickets[_ticketId] = Ticket({
            owner: msg.sender,
            eventId: _eventId,
            isUsed: false,
            exists: true
        });

        emit TicketCreated(_ticketId, _eventId, msg.sender);
    }

    /**
     * @dev Verify if a ticket is valid (exists, owned by address, not used)
     * @param _ticketId the ID of the ticket to verify
     */
    function verifyTicket(string memory _ticketId) public view returns (bool, address, string memory, bool) {
        require(tickets[_ticketId].exists, "Ticket does not exist");
        Ticket memory t = tickets[_ticketId];
        return (t.exists, t.owner, t.eventId, t.isUsed);
    }

    /**
     * @dev Mark a ticket as used
     * @param _ticketId the ID of the ticket
     */
    function markTicketUsed(string memory _ticketId) public {
        require(tickets[_ticketId].exists, "Ticket does not exist");
        require(!tickets[_ticketId].isUsed, "Ticket already used");
        
        // Either the owner or an admin can mark it as used. Currently anyone can call this if they have the ticket id, in reality only the event admin should scan.
        // We will allow anyone to mark it for simplicity, but ideally we'd add an admin check if needed.
        
        tickets[_ticketId].isUsed = true;

        emit TicketUsed(_ticketId, tickets[_ticketId].eventId);
    }
}
